# Generated by Django 5.0.6 on 2024-06-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPlantas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
