# Generated by Django 5.0.6 on 2024-06-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPlantas', '0002_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
