# Generated by Django 5.0.6 on 2024-06-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPlantas', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='productos/'),
        ),
    ]
